language: java
install: skip

os: linux
dist: trusty
jdk: oraclejdk11

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - ./gradlew build test

deploy:
  provider: heroku
  api_key:
    secure: 049c2eee-5e08-44a3-bcff-2b2df8d62966
  app: akoylu-service