management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'
    enabled-by-default: true
